version: "2"

linters:
  default: all
  disable:
    # deprecated: by golangci-lint
    - wsl
    # temp: skip for now
    - revive
    - depguard
  settings:
    gocritic:
      enable-all: true
    wrapcheck:
      ignore-package-globs:
        - github.com/therenotomorrow/ex

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/therenotomorrow/pusher)
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
      chain-split-dots: true

issues:
  fix: true
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

run:
  go: "1.25"
  allow-parallel-runners: true
  timeout: 5m
